In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv('../data/internships.csv')

df.shape
df.columns.tolist()
df.head()

,internship_id,Date Time,profile,company,Location,Start Date,Stipend,Duration,Apply by Date,Skills,Eligibility,Perks,Description,deadline_is_demo,domain,work_mode,internship_type
0,2025WSHP0080,2025-09-21 15:24:28,Full Stack Developer,Cogent Web Services,Work from home,Immediately,"₹ 10,000 /month",3 Months,11 Oct' 25,"HTML, CSS, JavaScript, React.js, Node.js",Postgraduate,"Certificate, Letter Of Recommendation",This Full Stack Development internship is focu...,False,Web Development,Remote,Technical
1,2025WSHP0165,2025-09-21 15:58:52,UI/UX Design,Eduminatti,Work from home,Immediately,"₹ 5,000 - 10,000 /month",2 Months,18 Oct' 25,"Figma, UI Design, UX Design, Wireframing, Prot...",Postgraduate & Undergraduate,"Certificate, Letter Of Recommendation",This UI/UX Design internship is focused on des...,True,UI / UX,Remote,Technical
2,2025WSHP0242,2025-09-21 16:13:20,Frontend Developer,LSOYS Games & Apps,Work from home,Immediately,"₹ 1,000 /month",6 Months,20 Sep' 25,"HTML, CSS, JavaScript, React.js, TypeScript",Postgraduate & Undergraduate,"Certificate, Letter Of Recommendation",This Web Development internship is focused on ...,True,Web Development,Remote,Technical
3,2025WSHP0016,2025-09-27 23:11:11,Frontend Developer,InstaWeb Labs Private Limited,Mumbai,Immediately,"₹ 10,000 - 15,000 /month",6 Months,8 Oct' 25,"HTML, CSS, JavaScript, React.js, TypeScript",Postgraduate,"Certificate, Flexible, Letter Of Recommendatio...",This Front End Development internship is focus...,False,Web Development,Hybrid,Technical
4,2025WSHP0513,2025-09-21 16:02:53,Flutter Development,Pragament Tech Solutions Private Limited,Work from home,Immediately,"₹ 1,001 - 5,000 /month",1 Month,16 Sep' 25,"Dart, Flutter, Firebase, REST API, Git",Undergraduate,"Certificate, Flexible, Letter Of Recommendatio...",This Flutter Development internship is focused...,True,Software Development,Remote,Technical

In [16]:
df.tail()

,internship_id,Date Time,profile,company,Location,Start Date,Stipend,Duration,Apply by Date,Skills,Eligibility,Perks,Description,deadline_is_demo,domain,work_mode,internship_type
195,2025WSHP0603,2025-09-27 22:39:04,Media & Public Relations (PR),Veritas Reputation PR Private Limited,Mumbai,Immediately,"₹ 5,000 - 10,000 /month",2 Months,22 Oct' 25,"Content Writing, Creative Writing, English Pro...",Postgraduate,"Certificate, 5 Days A Week",This Media & Public Relations (PR) internship ...,NaN,NaN,On-site,Non-Technical
196,2025WSHP0202,2025-09-27 21:47:17,Market Research,Suspol Technologies Private Limited,Greater Noida,Immediately,"₹ 7,000 - 10,000 /month",3 Months,8 Oct' 25,"Canva, English Proficiency (Spoken), English P...",Postgraduate & Undergraduate,"Certificate, Flexible, Letter Of Recommendatio...",This Market Research internship is focused on ...,NaN,NaN,On-site,Research
197,2025WSHP1518,2025-09-27 20:54:31,Business Research,SCDND ESTATES PRIVATE LIMITED,Greater Noida,Immediately,"₹ 9,000 - 13,000 /month",3 Months,18 Oct' 25,"English Proficiency (Spoken), English Proficie...",Undergraduate,"Certificate, Letter Of Recommendation, 5 Days ...",This Business Research internship is focused o...,NaN,NaN,On-site,Research
198,2025WSHP0769,2025-09-27 21:11:47,Research & Insights,Caarya,Chennai,Immediately,"₹ 7,000 - 15,000 /month",2 Months,22 Oct' 25,"Attention to Detail, Email Management, Google ...",Postgraduate,"Certificate, Flexible, Letter Of Recommendation",This Research & Insights internship is focused...,NaN,NaN,On-site,Research
199,2025WSHP3928,2025-09-27 21:06:39,Legal Research,Janus Law Associates,Delhi,Immediately,"₹ 2,500 /month",3 Months,24 Oct' 25,"Artificial intelligence, Computer skills, Engl...",Undergraduate,"Certificate, Flexible",This Legal Research internship is focused on r...,NaN,NaN,Hybrid,Research

In [17]:
df.nunique()

internship_id       200
Date Time           123
profile              61
company              73
Location             13
Start Date            3
Stipend              46
Duration              6
Apply by Date       112
Skills              162
Eligibility           4
Perks                12
Description         200
deadline_is_demo      2
domain                7
work_mode             3
internship_type       3
dtype: int64

In [18]:
df['company'].duplicated().sum()

np.int64(127)

In [19]:
df["company"].nunique()

73

In [20]:
df["company"].unique()

<StringArray>
[                                   'Cogent Web Services',
                                             'Eduminatti',
                                     'LSOYS Games & Apps',
                          'InstaWeb Labs Private Limited',
               'Pragament Tech Solutions Private Limited',
                                                'Lawtech',
                                              'Innovexis',
                                        'Tax-O-Smart LLP',
              'Axe Consultancy And Security Services LLC',
                       'Zoxima Solutions Private Limited',
                                'Tisteps Private Limited',
               'Tisteps Private Limited (Chennai, India)',
                          'NDFM Business World Pvt. Ltd.',
                                         'Digital Heroes',
                                       'APEX ENGINEERING',
                     'Emoolar Technology Private Limited',
                        'Aidea Solutions Private Limited',
                                  'Savant Consulting LLC',
                                          'Thermaissance',
                                             'EvolSkills',
          'Go Eleventh Mile Technologies Private Limited',
                                          'Primetrade.ai',
                                 'Nebulytix Technologies',
                  '4x4 Advisory Services Private Limited',
                                         'InnovateX Labs',
                                              'CyberGrid',
                                     'TechNova Solutions',
                                              'DevSphere',
                                           'Visionary AI',
                                         'CodeCraft Labs',
                                             'PixelStack',
                                            'QuantumSoft',
                                   'NextGen Technologies',
                                     'Axiom Technologies',
                                               'AppVerse',
                                              'ByteWorks',
                                       'CoreTech Systems',
                                             'StackOrbit',
                                            'CloudMatrix',
                                            'Nexora Labs',
                                              'LogicLeaf',
                                              'DataForge',
                                              'AlgoWorks',
                                             'TechBridge',
                        'Cars24 Services Private Limited',
                                     'Brand Scale-Up Inc',
                                     'Kenovate Solutions',
                                           'Serene Homes',
                                             'Echo Booom',
                      'Truevisory Realty Private Limited',
                      'Arbhu Enterprises Private Limited',
                                    'Namastu Enterprises',
                                                 'Houzeo',
                                           'The Monsha's',
                                             'Raja Tyagi',
                         'Swayam Infinty Private Limited',
                                                  'Swipe',
                                      'Amanat Foundation',
                        'Edculcate India Private Limited',
                                      'Moonstone Hammock',
                                               'Vamaship',
                                   'BOXIFIED Enterprises',
                            'Bajrangi Welfare Federation',
                                           'Aawas Yojana',
                                     'Kinetic Management',
                                          'Zypp Electric',
                           'Essential Services Outsource',
 'Get Structured Consulting Services OPC Private Limited',
                  'Veritas Reputation PR Private Limited',
                    'Suspol Technologies Private Limited',
                          'SCDND ESTATES PRIVATE LIMITED',
                                                 'Caarya',
                                   'Janus Law Associates']
Length: 73, dtype: str

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   internship_id     200 non-null    str
 1   Date Time         200 non-null    str
 2   profile           200 non-null    str
 3   company           200 non-null    str
 4   Location          200 non-null    str
 5   Start Date        200 non-null    str
 6   Stipend           200 non-null    str
 7   Duration          200 non-null    str
 8   Apply by Date     200 non-null    str
 9   Skills            200 non-null    str
 10  Eligibility       200 non-null    str
 11  Perks             200 non-null    str
 12  Description       200 non-null    str
 13  deadline_is_demo  170 non-null    object
 14  domain            170 non-null    str
 15  work_mode         200 non-null    str
 16  internship_type   200 non-null    str
dtypes: object(1), str(16)
memory usage: 26.7+ KB

In [22]:
df.isnull().sum()

internship_id        0
Date Time            0
profile              0
company              0
Location             0
Start Date           0
Stipend              0
Duration             0
Apply by Date        0
Skills               0
Eligibility          0
Perks                0
Description          0
deadline_is_demo    30
domain              30
work_mode            0
internship_type      0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df['internship_id'].duplicated().sum()

np.int64(0)

In [25]:
''' Phase 1 — Final Conclusion

Humne dataset me ye verify kar liya:

200 internships
13 columns
No actual null values found
eligibility → 3 categories
location → 26 unique values
role → 200 unique values
skills → 193 unique combinations
description → 200 unique descriptions
stipend → mixed text format
duration → mixed/dirty values
location → Remote / Work from home ko later standardize karna hoga
duration → 1 week ago, 3 weeks ago jaise suspicious values identify hue
stipend → ranges, single values, Unpaid, Not Available identify hue'''

' Phase 1 — Final Conclusion\n\nHumne dataset me ye verify kar liya:\n\n200 internships\n13 columns\nNo actual null values found\neligibility → 3 categories\nlocation → 26 unique values\nrole → 200 unique values\nskills → 193 unique combinations\ndescription → 200 unique descriptions\nstipend → mixed text format\nduration → mixed/dirty values\nlocation → Remote / Work from home ko later standardize karna hoga\nduration → 1 week ago, 3 weeks ago jaise suspicious values identify hue\nstipend → ranges, single values, Unpaid, Not Available identify hue'

In [26]:
#Phase 2 — Data Preprocessing